### ISSUE TITLE
Confirmed working on PC1640

### ISSUE THREAD

**Issue by wmoindrot** [somhi/AmstradXTPS2#1]
Hi, just to confirm that this setup is working with an Amstrad PC1640: the adapter successfully allowing a kayboard with PS/2 interface be plugged in and recognised by the computer. When you first boot you get a 'check keyboard or mouse' message flash for approx 5 seconds but this then goes and boot continues. When you arrive at the dos prompt the keyboard is functional. From minimal testing there does not seem to be any key translationg or timing problems.

One thing I did want to do was use this in combination with a D-Link KVM (an old style DVKM-4). But here it seems like the adapter cannot talk to the KVM, just checking my connection

**Comment by somhi** [comment]
Great, thanks for letting me know.

**Comment by wmoindrot** [comment]
Hi @somhi thanks again on the putting this together. I did check my connections to my KVM and they were all correct, so guessing there is something between the detection or handshake initiated between the the KVM and the Arduino setup. Not an issue with your adapter though! Thanks, Will

**Comment by Fing972** [comment]
Good evening,
I have a PC1640 and I created the project since I don't have an original keyboard and I want to adapt a PS2 keyboard.
When I turn on the PC it takes a few seconds after the "check keyboard or mouse" message and then it boots and then the PS2 keyboard works without problems.
When I reset the pc with the CTRL-ATL-DEL combination, the boot procedure stops at the "check keyboard or mouse" message. 
If I turn the computer off and on again I have no problems.
Is there anything to check in the Arduino code or could it be a hardware problem with the PC ? I created the project first with an Arduino Uno and then with an Arduino Nano and I have the same problem.
Thank you.
